version: '1.0'
services:
  ahashesh-ctf-findme:
    container_name: ahashesh-ctf-findme
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
    - '3000:80'
    networks:
      nw0:

networks:
  nw0:
    external: true