name: Find me!
description: |
  This CTF requires PHP knowledge.
  
  You will be presented with a web interface written in PHP and ReactJS,
  this interface allows you to upload any file to the server! The flag is hidden somewhere on the page, your job is to try to find it!
  
  This challenge will show how it's important to restrict features to their intended purpose only.
  
  **Connection Instructions**:
  
  Do the following:

  $ `ssh -L localhost:<local port>:container_ip:container_port -p 56151 <username>@cs561.cs.umass.edu`
  
  For example, run

  $ `ssh -L localhost:8080:ahashesh-ctf-findme:80 -p 56151 user@cs561.cs.umass.edu`

  This will forward the local port 8080 on your machine to ahashesh-ctf-findme:80 on the swarm network, where this challenge is hosted.

  Know you just need to open `localhost:<local port>` on you web browser.

  **Note**:

  It is recommended that you try the challenge on Google Chrome.

value: 200
category: Web Hacking
flag: f1@9_F1Nd_M3!211

# administrative
container_name: ahashesh-ctf-findme
